version: '3.7'

services:
  db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     env_file: local.env
  
  wordpress:
    depends_on:
      - db
    build: .
    image: paystack-wordpress-image
    ports:
      - "8000:80"
    env_file: local.env
volumes:
  db_data: {}
